version: '3'
services:
  php:
    build:
      context: .dockerfiles
      dockerfile: DockerfileBack 
    tty: true
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    command: php -S 0.0.0.0:80 -t app/public/
    networks:
      - app-network
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - 3306:3306
    networks:
      - app-network
  node:
    image: node:18.20.2
    tty: true
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - 5173:5173   
    networks:
      - app-network
    depends_on:
      - php
networks:
  app-network:
    driver: bridge